<?php

return [
    'agreement_version' => '2026-08-18',

    'templates' => [
        'socal_divorce_intake' => [
            'label' => 'Divorce Mediation Intake Questionnaire',
            'version' => 1,
            'source_pdf' => 'questionnaires/DIVORCE MEDIATION INTAKE QUESTIONNAIRE.pdf',
            'requires_agreement' => true,
            'fields' => [
                ['name' => 'preferred_language', 'label' => 'Preferred language', 'type' => 'select', 'options' => ['English', 'Spanish', 'Other']],
                ['name' => 'other_language', 'label' => 'Other language', 'type' => 'text'],
                ['name' => 'relationship_summary', 'label' => 'Briefly describe the relationship and current situation', 'type' => 'textarea'],
                ['name' => 'currently_living_together', 'label' => 'Are you currently living together?', 'type' => 'boolean'],
                ['name' => 'domestic_violence_history', 'label' => 'Is there any history of domestic violence or restraining orders?', 'type' => 'textarea'],
                ['name' => 'children_together', 'label' => 'Do you have children together?', 'type' => 'boolean'],
                ['name' => 'children_details', 'label' => 'Children names, ages, and living arrangements', 'type' => 'textarea'],
                ['name' => 'custody_concerns', 'label' => 'Custody, visitation, school, medical, relocation, or communication concerns', 'type' => 'textarea'],
                ['name' => 'child_support_status', 'label' => 'Has child support been discussed or ordered?', 'type' => 'textarea'],
                ['name' => 'spousal_support_expectation', 'label' => 'Are you requesting or expecting spousal support?', 'type' => 'textarea'],
                ['name' => 'asset_summary', 'label' => 'Family home, other properties, accounts, retirement, business interests, investments, and personal property', 'type' => 'textarea'],
                ['name' => 'debt_summary', 'label' => 'Describe debts, loans, credit cards, or other financial obligations', 'type' => 'textarea'],
                ['name' => 'case_filed_status', 'label' => 'Has a divorce case already been filed?', 'type' => 'textarea'],
                ['name' => 'attorney_involvement', 'label' => 'Are attorneys currently involved?', 'type' => 'textarea'],
                ['name' => 'preferred_session_format', 'label' => 'Preferred mediation format', 'type' => 'select', 'options' => ['In person', 'Zoom', 'Hybrid']],
                ['name' => 'same_room_comfort', 'label' => 'Are you comfortable being in the same room as the other party?', 'type' => 'textarea'],
                ['name' => 'goals_for_mediation', 'label' => 'What do you hope to accomplish in mediation?', 'type' => 'textarea'],
                ['name' => 'additional_information', 'label' => 'Anything else the mediator should know?', 'type' => 'textarea'],
            ],
        ],

        'socal_party_mediation' => [
            'label' => 'Party Mediation Questionnaire',
            'version' => 1,
            'source_pdf' => 'questionnaires/PARTY MEDIATION QUESTIONNAIRE.pdf',
            'requires_agreement' => true,
            'fields' => [
                ['name' => 'name', 'label' => 'Name', 'type' => 'text'],
                ['name' => 'date', 'label' => 'Date', 'type' => 'date'],
                ['name' => 'other_party_name', 'label' => 'Other party name', 'type' => 'text'],
                ['name' => 'case_or_matter', 'label' => 'Case or matter, if any', 'type' => 'text'],
                ['name' => 'dispute_summary', 'label' => 'What is this dispute about?', 'type' => 'textarea'],
                ['name' => 'problem_started_at', 'label' => 'When did the problem start?', 'type' => 'textarea'],
                ['name' => 'main_concern', 'label' => 'What is your main concern?', 'type' => 'textarea'],
                ['name' => 'personal_contribution', 'label' => 'What do you think you may have done that contributed to the problem?', 'type' => 'textarea'],
                ['name' => 'impact', 'label' => 'How has this dispute affected you?', 'type' => 'textarea'],
                ['name' => 'desired_result', 'label' => 'What do you want to happen as a result of mediation?', 'type' => 'textarea'],
                ['name' => 'acceptable_solution', 'label' => 'What solution would be acceptable to you?', 'type' => 'textarea'],
                ['name' => 'unacceptable_result', 'label' => 'What result would not be acceptable?', 'type' => 'textarea'],
                ['name' => 'mediation_goals', 'label' => 'Mediation goals', 'type' => 'checkboxes', 'options' => ['Financial settlement', 'Resolve misunderstandings', 'Repair or improve relationship', 'Set clear boundaries or rules', 'Avoid court', 'Other']],
                ['name' => 'other_goal', 'label' => 'Other mediation goal', 'type' => 'text'],
                ['name' => 'important_information', 'label' => 'Other important information for the mediator', 'type' => 'textarea'],
                ['name' => 'signature_name', 'label' => 'Signature name', 'type' => 'text'],
                ['name' => 'signature_date', 'label' => 'Signature date', 'type' => 'date'],
            ],
        ],

        'legal_initial_intake' => [
            'label' => 'Initial Intake Questionnaire',
            'version' => 1,
            'source_pdf' => 'questionnaires/Initial Intake [Filllable].pdf',
            'requires_agreement' => false,
            'fields' => [
                ['name' => 'previous_consultation', 'label' => 'Have you previously consulted with this office?', 'type' => 'boolean'],
                ['name' => 'name', 'label' => 'Name', 'type' => 'text'],
                ['name' => 'address', 'label' => 'Address', 'type' => 'textarea'],
                ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
                ['name' => 'alternate_email', 'label' => 'Alternate email', 'type' => 'email'],
                ['name' => 'phone', 'label' => 'Phone', 'type' => 'text'],
                ['name' => 'matter_type', 'label' => 'Type of legal matter', 'type' => 'checkboxes', 'options' => ['Family', 'Divorce', 'Custody', 'Support', 'Civil', 'Business', 'Real estate', 'Other']],
                ['name' => 'other_matter_type', 'label' => 'Other matter type', 'type' => 'text'],
                ['name' => 'reason_for_visit', 'label' => 'Reason for your visit today', 'type' => 'textarea'],
                ['name' => 'desired_outcome', 'label' => 'What outcome are you seeking?', 'type' => 'textarea'],
                ['name' => 'additional_information', 'label' => 'Additional information', 'type' => 'textarea'],
            ],
        ],
    ],
];
